@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package com.obsidian_core.archaic_quest.common.block;

import net.minecraft.MethodsReturnNonnullByDefault;
import javax.annotation.ParametersAreNonnullByDefault;